<a href="https://colab.research.google.com/github/Alfredzzx/Linear-Algebra-58020/blob/main/MID_TERM_EXAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

QUESTION 1

In [14]:
import numpy as np #import Library
#square matrix is same length and wdth therefore it is 5x5 matrix
SquareMatrix = np.array ([[1,2,3,4,5],[2,0,0,0,0],[3,0,0,0,0],[4,0,0,0,0],[5,0,0,0,0]]) #5x5 matrix
print("This is an example of square matrix whose length is 5") #this section is optional
print() #this is for spacing and also optional
print(SquareMatrix) #this is the final answer

This is an example of square matrix whose length is 5

[[1 2 3 4 5]
 [2 0 0 0 0]
 [3 0 0 0 0]
 [4 0 0 0 0]
 [5 0 0 0 0]]


QUESTION 2

In [16]:
#import Library
SM= np.array ([[0,1,1,1],[1,0,1,1],[1,1,0,1],[1,1,1,0]]) #a square matrix
print(SM)

[[0 1 1 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]]


QUESTION 3

In [17]:
#Create a symmetrical matrix
G = np.array([[1,2,3,4,5],[2,1,2,3,4],[3,2,1,2,3],[4,3,2,1,2],[5,4,3,2,1]])
print(G)

[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


QUESTION 4


In [9]:
import numpy as np
C = np.array ([[1,2,3],
               [2,3,3],
               [3,4,-2]])

invC = np.linalg.inv(C)

print("Inverse of Matrix C:")
print(invC)

Inverse of Matrix C:
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


QUESTION 5

In [10]:
import numpy as np
C = np.array ([[1,2,3],
               [2,3,3],
               [3,4,-2]])

detOfC = np.linalg.det(C)

print("Determinant of the given matrix in Question 4:")
print(int(detOfC))

Determinant of the given matrix in Question 4:
5


QUESTION 6 

In [13]:
import numpy as np
eq = np.array([[5,4,1],
               [10,9,4],
               [10,13,15]])

const = np.array([[[3.4],
                   [8.8],
                   [19.2]]])

roots = np.linalg.inv(eq) @ const

print("Roots of the given linear equations:")
print(roots)


Roots of the given linear equations:
[[[0.2]
  [0.4]
  [0.8]]]
