<a href="https://colab.research.google.com/github/Alfredzzx/Linear-Algebra-58020/blob/main/Practical_Exam_lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#numpy
import numpy as np
W = np.array([[1,-3],[2,-2],[3,1]])
print(W)
print()
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
print(X)
print()
Y = np.array([[1,2,0],[0,-1,2]])
print(Y)
print()
Z = np.array([[0,1],[2,3]])
print(Z)
print()
dot = np.dot(W,Y)
print(dot)
print()
print(Z+Z)
print()
dot = np.dot(3,X)
print(dot)
print()

[[ 1 -3]
 [ 2 -2]
 [ 3  1]]

[[ 3  2  1]
 [-1  2  3]
 [ 2 -1  1]]

[[ 1  2  0]
 [ 0 -1  2]]

[[0 1]
 [2 3]]

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]

[[0 2]
 [4 6]]

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]

