<a href="https://colab.research.google.com/github/Alfredzzx/Linear-Algebra-58020/blob/main/Practical_Exam_lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1

In [1]:
#numpy
import numpy as np
W = np.array([[1,-3],[2,-2],[3,1]])
print(W)
print()
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
print(X)
print()
Y = np.array([[1,2,0],[0,-1,2]])
print(Y)
print()
Z = np.array([[0,1],[2,3]])
print(Z)
print()
dot = np.dot(W,Y)
print(dot)
print()
print(Z+Z)
print()
dot = np.dot(3,X)
print(dot)
print()

[[ 1 -3]
 [ 2 -2]
 [ 3  1]]

[[ 3  2  1]
 [-1  2  3]
 [ 2 -1  1]]

[[ 1  2  0]
 [ 0 -1  2]]

[[0 1]
 [2 3]]

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]

[[0 2]
 [4 6]]

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]



Problem 2


In [2]:
#2) A
Y = np.array([[1, 2, 0],[0,-1,2]])
W = np.array([[1, -3],[2,-2],[3,1]])

print(np.dot(Y,W)^2)

[[ 7 -5]
 [ 6  6]]


In [3]:
#2) B
import numpy as np
W = np.array([[1, -3],[2,-2],[3,1]])
print('Vector W is', W)

Vector W is [[ 1 -3]
 [ 2 -2]
 [ 3  1]]


In [4]:
import numpy as np
Y = np.array([[1, 2, 0],[0,-1,2]])
print('Vector Y is', Y)

Vector Y is [[ 1  2  0]
 [ 0 -1  2]]


In [5]:
import numpy as np
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
print('Vector X is', X)

Vector X is [[ 3  2  1]
 [-1  2  3]
 [ 2 -1  1]]


In [6]:
R = np.dot(W,Y)
print(R)

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


In [7]:
print(np.subtract(R,X))
#2) B answer

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


In [8]:
#3) C
import numpy as np
W = np.array([[1, -3],[2,-2],[3,1]])
print('Vector W is', W)

Vector W is [[ 1 -3]
 [ 2 -2]
 [ 3  1]]


In [9]:
import numpy as np
Y = np.array([[1, 2, 0],[0,-1,2]])
print('Vector Y is', Y)

Vector Y is [[ 1  2  0]
 [ 0 -1  2]]


In [10]:
import numpy as np 
Z = np.array([[0,1],[2,3]])
print('Vector Z is', Z)

Vector Z is [[0 1]
 [2 3]]


In [11]:
print("(YW - Z^2)")
print(np.dot(Y,W)-Z^2)

(YW - Z^2)
[[ 7 -6]
 [ 0  3]]
